name: Build And Deploy Dokcer Image For Ell Cake Backend

on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push to Docker HUB
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: Dockerfile
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Login to Yandex Cloud Container Registry
        uses: yc-actions/yc-cr-login@v3
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_CI_CD_KEY_JSON }}

      - name: Pull from Docker Hub and Push to Yandex CR
        env:
          CR_REGISTRY_ID: ${{ vars.YC_REGISTRY_ID }}
          IMAGE_NAME: ${{ github.event.repository.name }}
          IMAGE_TAG: latest

        run: |
          docker pull ${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

          docker tag ${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
          cr.yandex/${{ env.CR_REGISTRY_ID }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

          docker push cr.yandex/${{ env.CR_REGISTRY_ID }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Deploy to Serverless Container
        uses: yc-actions/yc-sls-container-deploy@v3
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_CI_CD_KEY_JSON  }}
          container-name: ${{ vars.YC_CONTAINER_NAME }}
          folder-id: ${{ vars.YC_FOLDER_ID }}
          revision-service-account-id: ${{ secrets.YC_SA_ID }}
          revision-cores: 1
          revision-memory: 1024Mb
          revision-core-fraction: 100
          revision-image-url: cr.yandex/${{ vars.YC_REGISTRY_ID }}/${{ github.event.repository.name }}:latest
          revision-execution-timeout: 30
          revision-network-id: ${{ vars.YC_NETWORK_ID }}
          revision-env: |
            DATABASE_URL=${{ secrets.DATABASE_URL}}
            YC_S3_KEY_ID=${{ secrets.YC_S3_KEY_ID }}
            YC_S3_SECRET_KEY=${{ secrets.YC_S3_SECRET_KEY }}
            YC_S3_BUCKET=${{ vars.YC_S3_BUCKET }}
            YC_S3_REGION=${{ vars.YC_S3_REGION }}
            YC_S3_PRIVATE_ENDPOINT=${{ vars.YC_S3_PRIVATE_ENDPOINT }}
            SESSION_SECRET=${{ secrets.SESSION_SECRET }}
            FRONTEND_URL=${{ vars.FRONTEND_URL }}
            YOO_MONEY_SHOP_ID=${{ secrets.YOO_MONEY_SHOP_ID }}
            YOO_MONEY_SECRET_ID=${{ secrets.YOO_MONEY_SECRET_ID }}
            NODE_ENV=production
